// resources/ts/components/Input.vue
<script setup lang="ts">
withDefaults(
    defineProps<{
        size?: string;
        color?: string;
    }>(),
    {
        size: "base",
        color: "white",
    },
);
</script>

<template>
    <input
        class="el-input el-text el-bg el-ring el-outline el-border"
        :data-color="color"
        :data-size="size"
    />
</template>

// resources/ts/react/components/Input.tsx
import type { ComponentProps } from "react";
import clsx from "clsx";

type InputProps = ComponentProps<"input"> & { size?: string; color?: string };

export default function Input({ size = "base", color = "white", className, ...props }: InputProps) {
    return (
        <input
            {...props}
            className={clsx("el-input el-text el-bg el-ring el-outline el-border", className)}
            data-color={color}
            data-size={size}
        />
    );
}
