// resources/ts/components/Switch.vue
<script setup lang="ts">
withDefaults(
    defineProps<{
        disabled?: boolean;
        checked?: boolean;
        required?: boolean;
        color?: string;
        type?: string;
    }>(),
    {
        disabled: false,
        checked: false,
        required: false,
        color: "emerald",
        type: "checkbox",
    },
);
</script>

<template>
    <input
        class="el-switch"
        :data-color="color"
        :type="type"
        :disabled="disabled"
        :checked="checked"
        :required="required"
    />
</template>

// resources/ts/react/components/Switch.tsx
import type { ComponentProps } from "react";
import clsx from "clsx";
type SwitchProps = ComponentProps<"input"> & { color?: string };
export default function Switch({ color = "emerald", className, ...props }: SwitchProps) {
    return (
        <input
            {...props}
            className={clsx("el-switch", className)}
            data-color={color}
            type={props.type ?? "checkbox"}
        />
    );
}
