// resources/ts/react/components/Badge.tsx
import clsx from "clsx";
import type { ComponentProps } from "react";

type BadgeProps = ComponentProps<"span"> & {
    count?: number;
    max?: number;
    color?: string;
};

export default function Badge({
    count = 0,
    max = 99,
    color = "rose",
    className,
    ...props
}: BadgeProps) {
    const computedCount = count > 1 ? Math.min(count, max) : null;

    return (
        <span
            {...props}
            className={clsx(
                "el-badge el-text el-bg el-outline",
                count > 1 ? "size-5" : "size-3",
                className,
            )}
            data-color={color}
        >
            {computedCount}
        </span>
    );
}

// resources/ts/components/Badge.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(defineProps<{
  count?: number;
  max?: number;
  color?: string;
}>(), {
  count: 0,
  max: 99,
  color: 'rose',
});

const computedCount = computed(() => {
  return props.count > 1 ? Math.min(props.count, props.max) : null;
});
</script>

<template>
  <span :class="{
    'el-badge el-text el-bg el-outline': true,
    'size-5': count > 1,
    'size-3': count <= 1
  }" :data-color="color">
    {{ computedCount }}
  </span>
</template>
