// resources/ts/react/InputGroup.tsx
import type { ComponentProps, ReactNode } from "react";
import clsx from "clsx";
import InputIcon from "./InputIcon";

type InputGroupProps = ComponentProps<"div"> & {
    size?: string;
    color?: string;
    start?: ReactNode;
    icon?: ReactNode;
    iconRight?: ReactNode;
    end?: ReactNode;
};

export default function InputGroup({
    size = "base",
    color = "white",
    start,
    icon,
    iconRight,
    end,
    children,
    className,
    ...props
}: InputGroupProps) {
    return (
        <div
            {...props}
            className={clsx("el-input el-text el-bg el-outline el-border el-ring", className)}
            data-size={size}
            data-color={color}
        >
            {start}
            <div className="relative flex min-w-0 grow">
                {icon && <InputIcon>{icon}</InputIcon>}
                {children ?? <input type="text" />}
                {iconRight && <InputIcon>{iconRight}</InputIcon>}
            </div>
            {end}
        </div>
    );
}

// resources/ts/components/InputGroup.vue
<script setup lang="ts">
import InputIcon from "./InputIcon.vue";

withDefaults(
    defineProps<{
        size?: string;
        color?: string;
    }>(),
    {
        size: "base",
        color: "white",
    },
);
</script>

<template>
    <div
        class="el-input el-text el-bg el-outline el-border el-ring"
        :data-size="size"
        :data-color="color"
    >
        <slot name="start"></slot>

        <div class="relative flex min-w-0 grow">
            <InputIcon v-if="$slots.icon">
                <slot name="icon"></slot>
            </InputIcon>

            <slot>
                <input type="text" />
            </slot>

            <InputIcon v-if="$slots['icon-right']">
                <slot name="icon-right"></slot>
            </InputIcon>
        </div>

        <slot name="end"></slot>
    </div>
</template>
