// resources/ts/react/Popover.tsx
import {
    autoUpdate,
    flip,
    offset,
    shift,
    useDismiss,
    useFloating,
    useInteractions,
    useRole,
    type Placement,
} from "@floating-ui/react";
import { createFocusTrap, type FocusTrap } from "focus-trap";
import { createPortal } from "react-dom";
import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import clsx from "clsx";

type RenderProps = {
    trigger: Record<string, unknown>;
    show: () => void;
    hide: () => void;
    toggle: () => void;
    open: boolean;
};
type PopoverProps = {
    children: (props: RenderProps) => ReactNode;
    popover: (props: Omit<RenderProps, "trigger">) => ReactNode;
    trap?: boolean;
    placement?: Placement;
    offset?: number;
    animation?: false | string;
    backdrop?: boolean;
    role?: "dialog" | "menu" | "tooltip" | "listbox";
    className?: string;
};

export default function Popover({
    children,
    popover,
    trap = true,
    placement: requestedPlacement = "bottom",
    offset: offsetValue = 4,
    animation = "default",
    backdrop = true,
    role = "dialog",
    className,
}: PopoverProps) {
    const id = useId();
    const [open, setOpen] = useState(false);
    const [floatingElement, setFloatingElement] = useState<HTMLDivElement | null>(null);
    const focusTrap = useRef<FocusTrap | null>(null);
    const floating = useFloating({
        open,
        onOpenChange: setOpen,
        placement: requestedPlacement,
        middleware: [offset(offsetValue), flip({ crossAxis: false }), shift()],
        whileElementsMounted: autoUpdate,
    });
    const dismiss = useDismiss(floating.context, { outsidePress: true, escapeKey: true });
    const roleProps = useRole(floating.context, { role });
    const { getReferenceProps, getFloatingProps } = useInteractions([dismiss, roleProps]);
    const setFloating = (element: HTMLDivElement | null) => {
        floating.refs.setFloating(element);
        setFloatingElement(element);
    };
    const show = () => setOpen(true);
    const hide = () => setOpen(false);
    const toggle = () => setOpen((value) => !value);

    useEffect(() => {
        if (!open) return;
        if (trap && floatingElement) {
            focusTrap.current = createFocusTrap(floatingElement, { allowOutsideClick: true });
            focusTrap.current.activate();
        }
        return () => {
            focusTrap.current?.deactivate();
        };
    }, [floatingElement, open, trap]);

    const triggerAttrs = getReferenceProps({
        ref: floating.refs.setReference,
        ...(role === "tooltip" ? { "aria-describedby": open ? id : undefined } : {}),
    });

    const renderProps = { trigger: triggerAttrs, show, hide, toggle, open };

    return (
        <>
            {children(renderProps)}
            {open &&
                createPortal(
                    <>
                        {backdrop && <div className="el-popover-backdrop" />}
                        <div
                            ref={setFloating}
                            className={clsx("el-popover", className)}
                            id={id}
                            role={role}
                            {...getFloatingProps()}
                            style={floating.floatingStyles}
                            data-placement={floating.placement}
                            data-animation={animation || undefined}
                        >
                            {popover({ show, hide, toggle, open })}
                        </div>
                    </>,
                    document.body,
                )}
        </>
    );
}

// resources/ts/components/Popover.vue
<script setup lang="ts">
import {
    type ComponentPublicInstance,
    computed,
    type MaybeRefOrGetter,
    nextTick,
    ref,
    Teleport,
    toValue,
    useId,
    useTemplateRef,
    watch,
} from "vue";
import {
    autoUpdate,
    flip,
    type FlipOptions,
    offset,
    type OffsetOptions,
    type Placement,
    shift,
    type ShiftOptions,
    useFloating,
} from "@floating-ui/vue";
import { onClickOutside } from "@vueuse/core";
import { useFocusTrap } from "@vueuse/integrations/useFocusTrap";

defineOptions({
    inheritAttrs: false,
});

const props = withDefaults(
    defineProps<{
        trap?: MaybeRefOrGetter<boolean>;
        placement?: MaybeRefOrGetter<Placement>;
        offset?: MaybeRefOrGetter<OffsetOptions>;
        flip?: MaybeRefOrGetter<FlipOptions>;
        shift?: MaybeRefOrGetter<ShiftOptions>;
        animation?: MaybeRefOrGetter<false | string>;
        backdrop?: MaybeRefOrGetter<boolean>;
        role?: "dialog" | "menu" | "tooltip" | "listbox";
    }>(),
    {
        trap: true,
        offset: 4,
        placement: "bottom",
        animation: "default",
        backdrop: true,
        role: "dialog",
    },
);

const id = useId();

const open = defineModel<boolean>({
    default: false,
});

const trap = computed(() => toValue(props.trap));
const backdrop = computed(() => toValue(props.backdrop));
const animation = computed(() => toValue(props.animation));

const middleware = computed(() => [
    offset(toValue(props.offset)),
    flip({
        crossAxis: false,
        ...toValue(props.flip),
    }),
    shift(toValue(props.shift)),
]);

const trigger = ref<Element | ComponentPublicInstance | null>(null);

const floating = useTemplateRef("floating");

const { activate, deactivate } = useFocusTrap(floating, {
    allowOutsideClick: true,
});

const { isPositioned, floatingStyles, placement } = useFloating(trigger, floating, {
    middleware: middleware,
    whileElementsMounted: autoUpdate,
    open: open,
    placement: () => toValue(props.placement),
});

const setTrigger = (el: Element | ComponentPublicInstance | null) => {
    trigger.value = el;
};

watch([isPositioned, trap], ([value, trap], [oldValue, oldTrap]) => {
    if (trap) {
        if (value) {
            nextTick(() => activate());
        } else {
            nextTick(() => deactivate());
        }
    } else if (oldTrap) {
        nextTick(() => deactivate());
    }
});

function show() {
    open.value = true;
}
function hide() {
    open.value = false;
}
function toggle() {
    if (open.value) {
        hide();
    } else {
        show();
    }
}

const triggerAttrs = computed(() => {
    if (props.role === "tooltip") {
        return {
            ref: setTrigger,
            "aria-describedby": open.value ? id : undefined,
        };
    }

    return {
        ref: setTrigger,
        "aria-haspopup": props.role,
        "aria-expanded": open.value,
        "aria-controls": id,
    };
});

const triggerElement = computed(() => {
    if (trigger.value === null) {
        return undefined;
    }

    if (trigger.value instanceof HTMLElement) {
        return trigger;
    }

    if ("$el" in trigger.value) {
        return trigger.value.$el;
    }

    return null;
});

onClickOutside(
    floating,
    (e) => {
        hide();
    },
    {
        ignore: [triggerElement],
    },
);
</script>

<template>
    <slot :trigger="triggerAttrs" :show="show" :hide="hide" :toggle="toggle" :open="open"></slot>

    <Teleport to="body">
        <div v-if="backdrop && open" class="el-popover-backdrop"></div>
        <div
            v-if="open"
            v-bind="$attrs"
            :style="floatingStyles"
            ref="floating"
            class="el-popover"
            :data-placement="placement"
            :data-animation="animation || undefined"
            :role="role"
            :id="id"
            v-on:keydown.escape="hide"
        >
            <slot name="popover" :show="show" :hide="hide" :toggle="toggle" :open="open"></slot>
        </div>
    </Teleport>
</template>
