// resources/ts/react/components/Textarea.tsx
import { useEffect, useRef, useState, type ComponentProps } from "react";
import clsx from "clsx";
type TextareaProps = Omit<ComponentProps<"textarea">, "size"> & {
    rows?: number;
    size?: string;
    color?: string;
    autocomplete?: string;
    autosized?: boolean;
};
export default function Textarea({
    rows = 1,
    size = "base",
    color,
    autocomplete = "off",
    spellCheck = true,
    autosized = false,
    onInput,
    className,
    ...props
}: TextareaProps) {
    const textarea = useRef<HTMLTextAreaElement>(null);
    const [native, setNative] = useState(false);
    const resize = () => {
        if (textarea.current) {
            textarea.current.style.height = "0px";
            textarea.current.style.height = `${textarea.current.scrollHeight}px`;
        }
    };
    useEffect(() => {
        const supports = typeof CSS !== "undefined" && CSS.supports("field-sizing: content");
        setNative(supports);
        if (autosized && !supports) resize();
    }, [autosized]);
    return (
        <textarea
            {...props}
            {...{ autosized: autosized || undefined }}
            ref={textarea}
            className={clsx(
                "el-textarea el-spacing el-text el-bg el-ring el-outline el-border",
                className,
            )}
            data-size={size}
            data-color={color}
            rows={rows}
            spellCheck={spellCheck}
            autoComplete={autocomplete}
            data-1p-ignore={autocomplete === "off" || undefined}
            data-bwignore={autocomplete === "off" || undefined}
            data-lpignore={autocomplete === "off" ? "true" : undefined}
            data-form-type={autocomplete === "off" ? "other" : undefined}
            onInput={(event) => {
                if (autosized && !native) resize();
                onInput?.(event);
            }}
        />
    );
}

// resources/ts/components/Textarea.vue
<script setup lang="ts">
import { computed, onMounted, ref, useTemplateRef } from 'vue';


const props = withDefaults(defineProps<{
    rows?: number,
    size?: string,
    color?: string,
    autocomplete?: string,
    spellcheck?: boolean,
    autosized?: boolean,
}>(), {
    rows: 1,
    size: 'base',
    autocomplete: 'off',
    spellcheck: true,
    autosized: false,
});

const autocompleteAttributes = computed(() => {
    if (props.autocomplete === 'off') {
        return {
            'autocomplete': 'off',
            'data-1p-ignore': true,
            'data-bwignore': true,
            'data-lpignore': 'true',
            'data-form-type': 'other'
        };
    }
    return {
        'autocomplete': props.autocomplete,
    };
});

const native = ref(CSS.supports('field-sizing: content'));

const minHeight = ref(0);

const textarea = useTemplateRef('textarea');

function resize() {
    if (native.value === false && textarea.value) {
        textarea.value.style.height = `${minHeight}px`;
        textarea.value.style.height = `${textarea.value.scrollHeight}px`;
    }
}

const attributes = computed(() => {
    return autocompleteAttributes.value;
});

const listeners = computed(() => {
    return native.value ? {} : { input: resize };
});

onMounted(() => {
    if (native.value === false) {
        minHeight.value = textarea.value?.getBoundingClientRect().height ?? 0;

        resize();
    }
});
</script>

<template>
    <textarea ref="textarea" class="el-textarea el-text el-spacing el-bg el-outline" :data-size="size"
        :data-color="color" :autosized="autosized" :spellcheck="spellcheck" v-bind="attributes" v-on="listeners" />
</template>
