// resources/ts/react/Tooltip.tsx
import type { ReactNode } from "react";
import Popover from "./Popover";

type TooltipProps = {
    children: (props: {
        trigger: Record<string, unknown>;
        show: () => void;
        hide: () => void;
    }) => ReactNode;
    tooltip: ReactNode;
    className?: string;
};
export default function Tooltip({ children, tooltip, className }: TooltipProps) {
    return (
        <Popover
            trap={false}
            backdrop={false}
            role="tooltip"
            className={className}
            popover={() => <div className="el-tooltip">{tooltip}</div>}
        >
            {({ trigger, show, hide }) =>
                children({
                    trigger: {
                        ...trigger,
                        onMouseEnter: show,
                        onMouseLeave: hide,
                        onFocus: show,
                        onBlur: hide,
                    },
                    show,
                    hide,
                })
            }
        </Popover>
    );
}

// resources/ts/components/Tooltip.vue
<script setup lang="ts">
import { type MaybeRefOrGetter } from "vue";
import Popover from "./Popover.vue";
import { type Placement } from "@floating-ui/vue";

const props = withDefaults(
    defineProps<{
        trap?: MaybeRefOrGetter<boolean>;
        placement?: MaybeRefOrGetter<Placement>;
    }>(),
    {
        trap: false,
        placement: "top",
    },
);

const open = defineModel({
    default: false,
});
</script>

<template>
    <Popover v-model="open" :trap="trap" :placement="placement" :backdrop="false">
        <template v-slot:default="{ show, hide, trigger }">
            <slot
                :trigger="{
                    ...trigger,
                    onMouseenter: show,
                    onMouseleave: hide,
                    onFocus: show,
                    onBlur: hide,
                }"
                :show="show"
                :hide="hide"
            ></slot>
        </template>

        <template v-slot:popover>
            <div class="el-tooltip">
                <slot name="tooltip"></slot>
            </div>
        </template>
    </Popover>
</template>
