// resources/ts/react/components/Alert.tsx
import type { ComponentProps, ReactNode } from "react";
import clsx from "clsx";

type AlertProps = ComponentProps<"div"> & { color?: string; size?: string; icon?: ReactNode };

export default function Alert({
    color = "sky-light",
    size = "lg",
    icon,
    children,
    className,
    ...props
}: AlertProps) {
    return (
        <div
            {...props}
            className={clsx(
                "el-alert el-spacing el-text el-bg el-ring el-outline el-border el-shadow",
                className,
            )}
            data-color={color}
            data-size={size}
        >
            {icon && <span className="el-alert-icon -mx-1">{icon}</span>}
            {children}
        </div>
    );
}

// resources/ts/vue/components/Alert.vue
<script setup lang="ts">
withDefaults(
    defineProps<{
        color?: string;
        size?: string;
    }>(),
    {
        color: "sky-light",
        size: "lg",
    },
);
</script>

<template>
    <div
        class="el-alert el-spacing el-text el-bg el-ring el-outline el-border el-shadow"
        :data-color="color"
        :data-size="size"
    >
        <span class="el-alert-icon -mx-1" v-if="$slots.icon">
            <slot name="icon"></slot>
        </span>

        <div>
            <slot></slot>
        </div>
    </div>
</template>
