// resources/ts/react/components/Select.tsx
import type { ComponentProps } from "react";
import clsx from "clsx";

type SelectProps = ComponentProps<"select"> & { size?: string; color?: string };
export default function Select({
    size = "base",
    color = "white",
    className,
    ...props
}: SelectProps) {
    return (
        <select
            {...props}
            className={clsx("el-select el-text el-bg el-outline el-ring", className)}
            data-size={size}
            data-color={color}
        />
    );
}

// resources/ts/vue/components/Select.vue
<script setup lang="ts">
withDefaults(
    defineProps<{
        disabled?: boolean;
        required?: boolean;
        size?: string;
        color?: string;
    }>(),
    {
        size: "base",
        color: "white",
    },
);
</script>

<template>
    <select
        class="el-select el-text el-bg el-outline el-ring"
        :data-size="size"
        :data-color="color"
        :disabled="disabled || undefined"
        :required="required || undefined"
    >
        <slot></slot>
    </select>
</template>
